version: '3.9'

services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  artemis:
    image: webcenter/activemq
    ports:
      - 61616:61616
      - 8161:8161
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
      - ACTIVEMQ_USERS_websocketp2p=websocketp2p

