spring:
  application:
    name: websocket-peer-to-peer
  data:
    mongodb:
      uri: mongodb://admin:admin@127.0.0.1:27017/websocket-p2p?authSource=admin
  artemis:
    broker-url: tcp://localhost:61616
    user: websource-p2p
    password: websource-p2p
    embedded:
      queues: messaging

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
betvictor:
  application-hostname: http://localhost




